# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 486dcddae58f0b3454a8c59f8769927baf18ac18201c68b32ea2cc7d26ac81dba8a363f2e4f61281ef25f4348693662f398c96327c3a98e87d2f6f305929fa65

test:
  secret_key_base: 81db589dde30b2db782876ade1b1a3cb03358c4fb9f9360240c8f5a20f7f62fbd309b7ac2cda9b2b514558f3e5e3967e0fb25f35d736f204c8c036054d544efd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
